import { defineNuxtModule, useNuxt } from 'nuxt/kit'
import { join } from 'node:path'
import { appendFileSync, existsSync, readFileSync } from 'node:fs'
import { randomUUID } from 'node:crypto'

export default defineNuxtModule({
  meta: {
    name: 'oauth',
  },
  setup() {
    const nuxt = useNuxt()
    if (nuxt.options._prepare || process.env.NUXT_SESSION_PASSWORD) {
      return
    }

    const envPath = join(nuxt.options.rootDir, '.env')
    const hasPassword =
      existsSync(envPath) && /^NUXT_SESSION_PASSWORD=/m.test(readFileSync(envPath, 'utf-8'))

    if (!hasPassword) {
      // eslint-disable-next-line no-console
      console.info('Generating NUXT_SESSION_PASSWORD for development environment.')
      const password = randomUUID().replace(/-/g, '')

      nuxt.options.runtimeConfig.sessionPassword = password
      appendFileSync(envPath, `# generated by dev module\nNUXT_SESSION_PASSWORD=${password}\n`)
    }
  },
})
